url: "https://kayrrtolkien24.github.io"
baseurl: ""

# Site settings
title: Kademos Consulting
email:
description: "Kademos is a leading provider of advanced data analytics and AI-driven business intelligence solutions."


# Team names, titles and social links
people:
- name: Olivia Martinez
  pic: 1
  position: Chief Data Scientist
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Ethan Carter
  pic: 2
  position: Head of Business Intelligence
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Sophia Nguyen
  pic: 3
  position: Lead Data Analyst
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/company/kademos-consulting/
  - title: facebook
    url:
  - title: stack-overflow
    url: 
  - title: bitbucket 
    url: 
  - title: github
    url: 

# Postal address (add as many lines as necessary)
address:

# Build settings
markdown: kramdown
permalink: pretty
